; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[USBNugget]
board = lolin_s2_mini

[env]
framework = arduino
platform = espressif32
lib_deps = 
	sandeepmistry/LoRa@^0.8.0
	git@github.com:RetiaLLC/EspTinyUSB.git
	adafruit/Adafruit NeoPixel@^1.12.0
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.5.0
	https://github.com/dojyorin/arduino_base64#c67be4c
	SD @ ^2.0.0




# if this is first flash, set this to true
; NUG_FIRST_FLASH=true
[env:USBNugget_FirstFlash]
board = ${USBNugget.board}
#extra_scripts = scripts/reset-scripts-during-flash.py

; flash: check-port build
	; docker create --name $(CONTAINER_NAME) --device=$(PORT) -t rubber-nugget:latest
	; docker start $(CONTAINER_NAME)
	; docker exec $(CONTAINER_NAME) bash -c \
		; './arduino-cli upload -b esp32:esp32:esp32s2 --port $(PORT) RubberNugget/ && sleep 2'
; ifeq ($(RESET_SCRIPTS_DURING_FLASH), true)
	; docker exec $(CONTAINER_NAME) bash -c \
		; 'python3 -m esptool --after no_reset write_flash 0x111000 build/$(FATFS)'
; endif
	; docker rm --force $(CONTAINER_NAME)
#RUN ./scripts/build_web_ui.sh
#ARG FATFS_OUTPUT_FILE
#ARG FATFS_FROM_DIR
#RUN mkdir build
#RUN OUTPUT_FILE=${FATFS_OUTPUT_FILE} DIR=${FATFS_FROM_DIR} ./fatfs/generate_fs.sh && mv ./fatfs/${FATFS_OUTPUT_FILE} ./build
#RUN ./arduino-cli compile -b esp32:esp32:esp32s2 RubberNugget \
#    --build-property build.partitions=noota_3gffat \
#    --build-property build.cdc_on_boot=1 \
#    --output-dir=./build


[env:USBNugget_Flash]
board = ${USBNugget.board}