name: USB-Nugget build

on:
  push:
    branches: [ main, bp-dev ]
    paths: [ "src/**" ]
  pull_request:
    branches: [ main, bp-dev ]
    paths: [ "src/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - with:
        repository: RetiaLLC/EspTinyUSB
        token: ${{ ESP_TINY_USB_PRIVATE_SSH_KEY }}
    - name: Build the Docker image
      run: |
        cd src
        make build
